// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Widgets.Data;

#nullable disable

namespace Widgets.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221114319_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GenreItem", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemsId")
                        .HasColumnType("TEXT");

                    b.HasKey("GenresId", "ItemsId");

                    b.HasIndex("ItemsId");

                    b.ToTable("ItemGenres", (string)null);
                });

            modelBuilder.Entity("Widgets.Data.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Widgets.Data.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%S','now')");

                    b.Property<string>("CoverPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Wishlist");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items", t =>
                        {
                            t.HasCheckConstraint("CK_Item_Rating", "Rating IS NULL OR (Rating >= 0 AND Rating <= 10)");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Widgets.Data.Models.Album", b =>
                {
                    b.HasBaseType("Widgets.Data.Models.Item");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Digital");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackCount")
                        .HasColumnType("INTEGER");

                    b.ToTable("Albums", t =>
                        {
                            t.HasCheckConstraint("CK_Item_Rating", "Rating IS NULL OR (Rating >= 0 AND Rating <= 10)");

                            t.HasCheckConstraint("CK_Album_Format", "Format IN ('Digital','Vinyl','CD','Cassette')");
                        });
                });

            modelBuilder.Entity("Widgets.Data.Models.Book", b =>
                {
                    b.HasBaseType("Widgets.Data.Models.Item");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Books", t =>
                        {
                            t.HasCheckConstraint("CK_Item_Rating", "Rating IS NULL OR (Rating >= 0 AND Rating <= 10)");
                        });
                });

            modelBuilder.Entity("Widgets.Data.Models.Manga", b =>
                {
                    b.HasBaseType("Widgets.Data.Models.Item");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Manga");

                    b.Property<int>("ReadChapters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ReadVolumes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalVolumes")
                        .HasColumnType("INTEGER");

                    b.ToTable("Mangas", t =>
                        {
                            t.HasCheckConstraint("CK_Item_Rating", "Rating IS NULL OR (Rating >= 0 AND Rating <= 10)");

                            t.HasCheckConstraint("CK_Manga_Origin", "Origin IN ('Manga','Manhwa','Manhua','Western', 'Novel')");
                        });
                });

            modelBuilder.Entity("Widgets.Data.Models.VideoWork", b =>
                {
                    b.HasBaseType("Widgets.Data.Models.Item");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamingService")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedEpisodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.ToTable("VideoWorks", t =>
                        {
                            t.HasCheckConstraint("CK_Item_Rating", "Rating IS NULL OR (Rating >= 0 AND Rating <= 10)");
                        });
                });

            modelBuilder.Entity("Widgets.Data.Models.Videogame", b =>
                {
                    b.HasBaseType("Widgets.Data.Models.Item");

                    b.Property<int>("Completion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<double>("HoursPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.ToTable("Videogames", t =>
                        {
                            t.HasCheckConstraint("CK_Item_Rating", "Rating IS NULL OR (Rating >= 0 AND Rating <= 10)");

                            t.HasCheckConstraint("CK_Game_Completion", "Completion >= 0 AND Completion <= 100");
                        });
                });

            modelBuilder.Entity("GenreItem", b =>
                {
                    b.HasOne("Widgets.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Widgets.Data.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Widgets.Data.Models.Album", b =>
                {
                    b.HasOne("Widgets.Data.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("Widgets.Data.Models.Album", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Widgets.Data.Models.Book", b =>
                {
                    b.HasOne("Widgets.Data.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("Widgets.Data.Models.Book", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Widgets.Data.Models.Manga", b =>
                {
                    b.HasOne("Widgets.Data.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("Widgets.Data.Models.Manga", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Widgets.Data.Models.VideoWork", b =>
                {
                    b.HasOne("Widgets.Data.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("Widgets.Data.Models.VideoWork", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Widgets.Data.Models.Videogame", b =>
                {
                    b.HasOne("Widgets.Data.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("Widgets.Data.Models.Videogame", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
